---
title: "Introduction"
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is a relational database?
- What is a spreadsheet?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain the difference between a relational database and a spreadsheet
- Explain the advantages and disadvantages

::::::::::::::::::::::::::::::::::::::::::::::::


## Introduction


::::::::::::: discussion

### Discussion: Do you use tables and if so, for which tasks?

Spreadsheets, like Microsoft Excel, are used in many areas of application, but they have their limits in many places. Have you noticed any limitations or problems in your work?

::::::::::::::::::::


Before we create a new database and fill it with information and data, we should learn the basic concept behind all this. What is a relational database or a spreadsheet, why should i use these and how do I organize my data to get the best use out of all these concepts.
To understand the starting point where we are coming from, we want to understand the basic idea behind the concepts.

## Spreadsheets

Spreadsheets are one of the most versatile and widely used tools for data analysis and management. They allow users to organize data in a flexible format that supports simple to complex calculations and analyses. Typically, spreadsheets consist of a grid of cells, organized in columns and rows, which can contain data such as text, numbers, and formulas.
One of the strengths of spreadsheets is their ease of use, which enables even non-experts to effectively manipulate and analyze data. Formulas and functions, like SUM, AVERAGE, and VLOOKUP, provide powerful ways to perform automatic calculations and consolidate data.
Moreover, modern spreadsheet programs like Microsoft Excel and Google Sheets support advanced features such as pivot tables, conditional formatting, and the integration of scripting languages like VBA and Google App Script, which allow for task automation and the creation of custom functions.
Spreadsheets are therefore indispensable in many business, academic, and private applications, where they are used for data storage, financial analysis, planning, and much more.

::::::::::::: discussion

### Discussion: Do you use databases and if so, for which tasks?

You may have heard of databases and maybe even use them, but do you know how they work and why they are used? Do you know advantages or disadvantages?

::::::::::::::::::::


## Relational Database

Relational databases form the foundation for storing and managing structured data in many modern projects. They are based on a model where data is organized in a tabular form, each table consisting of rows and columns. This structure allows efficient data storage, querying, and manipulation.
A key feature of relational databases is the use of primary and foreign keys that define strong relationships between different tables. These keys support data integrity and facilitate complex data queries involving multiple tables.
SQL (Structured Query Language) is the dominant language used for creating, managing, and querying relational databases. Its powerful commands like SELECT, INSERT, UPDATE, and DELETE enable users to interact with data and extract valuable insights from large datasets.
Overall, relational databases offer a robust and reliable solution for enterprise data management, ensuring high data quality and security through their structured and rule-based setup.



## What is NocoDB?

NocoDB combines exactly these two concepts and allows us to create databases with the clear interface of a spreadsheet. 
It is a so-called ‘no code database’, which makes it possible to set up and use a relational database without any coding experience. NocoDB also allows us to work collaboratively in a team and even enter and use data without a special account. NocoDB is also open source. This means that we could theoretically set up our own instance and thus create and use our data completely independently of others. It also offers many other options for connecting and utilising our data on the Internet, which we will not go into in this course.